// Array of team members. Edit this to change the Members in the team and fullTeam pages.

export const teamMembers = [
    {
        name: "Chris _",
        major: "Unknown",
        role: "Unknown",
        img: "assets/team + fullTeam pages/Members Photos/Chris.png",
        popup: "Chris is a major in Unknown and enjoys Unknown.",
        email: "Unkown",
    },
    {
        name: "Eva Grimes",
        major: "Unknown",
        role: "Unknown",
        img: "assets/team + fullTeam pages/Members Photos/Eva.jpg",
        popup: "Eva is a major in Unknown and enjoys Unknown.",
        email: "Unkown",
    },
    {
        name: "Jacob Blankenship",
        major: "Computer Science",
        role: "Software Developer",
        img: "assets/team + fullTeam pages/Members Photos/Jacob.png",
        popup: "Jacob is a major in Computer Science and enjoys Unknown.",
        email: "jackobblankenship095@gmail.com",
    },
    {
        name: "Ka'Veon Redd",
        major: "Computer Science",
        role: "Software Developer",
        img: "assets/team + fullTeam pages/Members Photos/KaVeon.png",
        popup: "Ka'Veon is a major in Computer Science and enjoys blending creativity with technology to explore and create innovative ideas.",
        email: "kaveon.redd.25@cnu.edu",
    },
    {
        name: "Logan _",
        major: "Unknown",
        role: "Unknown",
        img: "assets/team + fullTeam pages/Members Photos/Logan.png",
        popup: "Logan is a major in Unknown and enjoys Unknown.",
        email: "Unknown",
    },
    {
        name: "Marie _",
        major: "Unknown",
        role: "Unknown",
        img: "assets/team + fullTeam pages/Members Photos/Marie.png",
        popup: "Marie is a major in Unknown and enjoys Unknown.",
        email: "Unknown",
    },
    {
        name: "Maverick _",
        major: "Unknown",
        role: "Unknown",
        img: "assets/team + fullTeam pages/Members Photos/Maverick.png",
        popup: "Maverick is a major in Unknown and enjoys Unknown.",
        email: "Unknown",
    },
    {
        name: "Moxxie Schrader",
        major: "Electrical Engineering",
        role: "Software",
        img: "assets/team + fullTeam pages/Members Photos/Moxxie.jpg",
        popup: "Moxxie is a major in Electrical Engineering and enjoys Unknown.",
        email: "Moxxie.schrader.24@cnu.edu",
    },
    {
        name: "Zahira _",
        major: "Unknown",
        role: "Unknown",
        img: "assets/team + fullTeam pages/Members Photos/Zahira.png",
        popup: "Zahira is a major in Unknown and enjoys Unknown.",
        email: "Unknown",
    },
        {
        name: "Chris Jeffrey",
        major: "History",
        role: "Hardware",
        img: "https://picsum.photos/600/350?random=3",
        popup: "Chris is a major in History and enjoys reading .",
        email: "N/A",
    },
];